# Build stage
FROM node:18-slim AS build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Build your application
RUN npm run build

# Production stage
FROM node:18-slim AS production

WORKDIR /app

# Copy the built application from the previous stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./

# Make sure wait-for-it.sh is executable
COPY --from=build /app/wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

# Install only production dependencies
RUN npm ci --only=production

# Define the command to run your application
# Ensure that wait-for-it.sh is executable and properly waits for services
CMD ["sh", "-c", "./wait-for-it.sh rabbitmq:5672 --timeout=30 --strict -- ./wait-for-it.sh postgres:5432 --timeout=30 --strict -- npm start"]
